name: 'dbt_interview'
version: '1.0.0'
config-version: 2

profile: 'default'

flags:
  send_anonymous_usage_stats: false

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
docs-paths: ["docs"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_interview:
    +database: dbt
    +persist_docs:
      relation: true
      columns: true
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +schema: marts
      +materialized: table
    staging:
      +schema: staging
      +materialized: view

vars:
  "dbt_date:time_zone": "Europe/Berlin"

data_tests:
  dbt_interview:
    +store_failures: false
    +severity: error
    staging:
      +severity: warn
      +store_failures: false
    intermediate:
      +severity: error
      +store_failures: true
    marts:
      +severity: error
      +store_failures: true

on-run-start:
  - "{{ log('--- dbt run started at: ' ~ run_started_at ~ ' ---', info=true) }}"

on-run-end:
  - "{{ log('--- dbt run completed. Models: ' ~ results | length ~ ' ---', info=true) }}"
  - "{{ grant_select(schema_name='marts') }}"